#!/bin/bash

# sources:
# - https://medium.com/@linuxdevhub/how-to-bluetooth-device-auto-connect-after-ubuntu-login-b4f9c2e2551d
# - https://unix.stackexchange.com/questions/334386/how-to-set-up-automatic-connection-of-bluetooth-headset

HEADSET_ADDR="${1:-60:F4:3A:DE:5E:4D}"

bluetoothctl trust $HEADSET_ADDR &>/dev/null
bluetoothctl disconnect $HEADSET_ADDR &>/dev/null
bluetoothctl connect $HEADSET_ADDR &>/dev/null
