#!/bin/bash

D_DRIVE="/dev/sda2"
D_MOUNT="/mnt/D/"
WINDOWS_DRIVE="/dev/nvme0n1p3"
WINDOWS_MOUNT="/mnt/C/"

sudo ntfsfix $D_DRIVE
sudo mount -o rw $D_DRIVE 
sudo ntfs-3g -o remove_hiberfile $WINDOWS_DRIVE $WINDOWS_MOUNT

